services:
  cei_mysql:
    container_name: cei_mysql
    image: mysql:latest
    restart: unless-stopped

    volumes:
      - cei_mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    networks:
      - cei

  cei_next:
    container_name: cei_next
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - cei_mysql

    ports:
      - "3000:3000"

    networks:
      - cei

volumes:
  cei_mysql_data:
    name: cei_mysql-data
    driver: local

networks:
  cei:
    driver: bridge