name: cei-site

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      # Setup de Node
      - name: Setup de Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installation des dépendances
        run: npm install

      # Lint
      - name: Run Lint
        run: npm run lint

      # Prettier
      - name: Run Prettier
        run: npm run format
