name: cei-site

on:
  push:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup de Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installation des dépendances
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: lint 

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Log in to Docker Hub
  #     - name: Log in to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #     # Build and push Docker image
  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/cei_next:latest .
  #         docker push ${{ secrets.DOCKER_USERNAME }}/cei_next:latest

  #     # Trigger Portainer webhook to update the container
  #     - name: Trigger Portainer webhook
  #       run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
